export const CHANGE_STATUS_FETCHING = "CHANGE_STATUS_FETCHING";
export const CHANGE_STATUS_FULFILLED = "CHANGE_STATUS_FULFILLED";
export const SET_ERROR = "SET_ERROR";
export const SET_USER_DATA = "SET_USER_DATA";